# Generated by Django 5.2.7 on 2025-10-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('contact', 'Contact'), ('services', 'Services'), ('gallery', 'Gallery')], max_length=50, unique=True)),
                ('banner_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('file', models.FileField(upload_to='banners/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
