# Generated by Django 5.2.7 on 2025-10-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managerpanel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='file',
        ),
        migrations.AddField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/images/'),
        ),
        migrations.AddField(
            model_name='banner',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='banners/videos/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='page',
            field=models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('contact', 'Contact'), ('services', 'Services'), ('blog', 'Blog')], max_length=50, unique=True),
        ),
    ]
