# Generated by Django 5.2.7 on 2025-10-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managerpanel', '0002_remove_banner_file_banner_image_banner_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='page',
            field=models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('contact', 'Contact'), ('package', 'Package'), ('franchise', 'Franchise')], max_length=50, unique=True),
        ),
    ]
